/**
 * The RCCG regions and provinces MMPraise draws volunteers from.
 *
 * Generated from DIRECTORIES.xlsx, the organisation's own directory, by
 * generate-church-directory.mjs. Do not hand-edit — regenerate instead, so
 * the two cannot drift apart.
 *
 * Two things about this hierarchy are easy to get wrong:
 *
 *  1. Regions are numbered, not geographic. The state name appears in the
 *     province, never in the region — and ten regions span more than one
 *     state (Region 18 covers Kebbi, Sokoto and Zamfara), so a volunteer’s
 *     state cannot be inferred from their region.
 *  2. "Youth Province n" is not a place. It occupies the same slot as a
 *     geographic province and must never be parsed as one.
 *
 * Normalised on import: Title Case throughout; two rows missing the word
 * "Province" completed (Kwara 2, Cross Rivers 9); and the misspellings
 * Nassarawa and Cross Rivers corrected to Nasarawa and Cross River.
 *
 * Nigeria only. International regions are seeded separately under their own
 * continents and are untouched by this directory.
 */
export type ChurchRegionSeed = { name: string; provinces: string[] }

export const churchDirectory: ChurchRegionSeed[] = [
  {
    name: "Redemption City Region",
    provinces: [
      "Redemption City Province",
    ],
  },
  {
    name: "Region 1",
    provinces: [
      "Lagos Province 1",
      "Lagos Province 11",
      "Lagos Province 43",
      "Lagos Province 70",
      "Lagos Province 73",
      "Lagos Province 79",
      "Lagos Province 93",
      "Lagos Province 103",
      "Lagos Province 110",
      "Lagos Province 124",
    ],
  },
  {
    name: "Region 2",
    provinces: [
      "Lagos Province 8",
      "Lagos Province 13",
      "Lagos Province 50",
      "Lagos Province 56",
      "Lagos Province 87",
      "Lagos Province 95",
      "Lagos Province 111",
      "Lagos Province 125",
    ],
  },
  {
    name: "Region 3",
    provinces: [
      "Osun Province 2",
      "Osun Province 3",
      "Osun Province 5",
      "Osun Province 8",
      "Osun Province 9",
      "Osun Province 11",
      "Osun Province 12",
      "Osun Province 14",
      "Osun Province 16",
      "Osun Province 17",
      "Osun Province7",
    ],
  },
  {
    name: "Region 4",
    provinces: [
      "Kwara Province 1",
      "Kwara Province 2",
      "Kwara Province 3",
      "Kwara Province 4",
      "Kwara Province 5",
      "Kwara Province 6",
      "Kwara Province 7",
      "Kwara Province 8",
      "Kwara Province 9",
    ],
  },
  {
    name: "Region 5",
    provinces: [
      "Rivers Province 1",
      "Rivers Province 4",
      "Rivers Province 6",
      "Rivers Province 9",
      "Rivers Province 14",
      "Rivers Province 15",
      "Rivers Province 18",
      "Rivers Province 19",
    ],
  },
  {
    name: "Region 6",
    provinces: [
      "Ebonyi Province 1",
      "Ebonyi Province 2",
      "Ebonyi Province 3",
      "Enugu Province 1",
      "Enugu Province 2",
      "Enugu Province 3",
      "Enugu Province 4",
      "Enugu Province 5",
    ],
  },
  {
    name: "Region 7",
    provinces: [
      "Adamawa Province",
      "Adamawa Province 2",
      "Taraba Province",
      "Taraba Province 2",
    ],
  },
  {
    name: "Region 8",
    provinces: [
      "Plateau Province 1",
      "Plateau Province 2",
      "Plateau Province 3",
      "Plateau Province 4",
      "Plateau Province 5",
    ],
  },
  {
    name: "Region 9",
    provinces: [
      "Jigawa Province",
      "Kano Province",
      "Kano Province 2,",
      "Katsina Province",
    ],
  },
  {
    name: "Region 10",
    provinces: [
      "Fct Province 1",
      "Fct Province 4",
      "Fct Province 6",
      "Fct Province 12",
      "Fct Province 13",
      "Fct Province 15",
      "Fct Province 19",
      "Fct Province 21",
    ],
  },
  {
    name: "Region 11",
    provinces: [
      "Lagos Province 6",
      "Lagos Province 16",
      "Lagos Province 20",
      "Lagos Province 53",
      "Lagos Province 65",
      "Lagos Province 88",
      "Lagos Province 114",
    ],
  },
  {
    name: "Region 12",
    provinces: [
      "Ogun Province 4",
      "Ogun Province 5",
      "Ogun Province 8",
      "Ogun Province 11",
      "Ogun Province 18",
      "Ogun Province 20",
      "Ogun Province 22",
      "Ogun Province 23",
      "Ogun Province 30",
      "Ogun Province 31",
      "Ogun Province 33",
    ],
  },
  {
    name: "Region 13",
    provinces: [
      "Edo Province 1",
      "Edo Province 2",
      "Edo Province 4",
      "Edo Province 6",
      "Edo Province 9",
      "Edo Province 11",
      "Edo Province 13",
      "Edo Province 15",
      "Edo Province 16",
      "Edo Province 19",
    ],
  },
  {
    name: "Region 14",
    provinces: [
      "Akwa Ibom Province 3",
      "Akwa Ibom Province 5",
      "Akwa Ibom Province 6",
      "Akwa Ibom Province 7",
      "Akwa Ibom Province 9",
    ],
  },
  {
    name: "Region 15",
    provinces: [
      "Abia Province 1",
      "Abia Province 2",
      "Abia Province 3",
      "Abia Province 4",
      "Abia Province 5",
      "Abia Province 6",
    ],
  },
  {
    name: "Region 16",
    provinces: [
      "Borno Province",
      "Yobe Province",
    ],
  },
  {
    name: "Region 17",
    provinces: [
      "Bauchi Province",
      "Bauchi Province 2",
      "Gombe Province",
      "Gombe Province 2",
    ],
  },
  {
    name: "Region 18",
    provinces: [
      "Kebbi Province",
      "Sokoto Province",
      "Zamfara Province",
    ],
  },
  {
    name: "Region 19",
    provinces: [
      "Lagos Province 2",
      "Lagos Province 23",
      "Lagos Province 27",
      "Lagos Province 40",
      "Lagos Province 60",
      "Lagos Province 77",
      "Lagos Province 89",
      "Lagos Province 92",
      "Lagos Province 115",
      "Lagos Province 118",
      "Lagos Province 126",
      "Lagos Province 127",
    ],
  },
  {
    name: "Region 20",
    provinces: [
      "Lagos Province 4",
      "Lagos Province 15",
      "Lagos Province 34",
      "Lagos Province 35",
      "Lagos Province 47",
      "Lagos Province 67",
      "Lagos Province 119",
      "Lagos Province 131",
    ],
  },
  {
    name: "Region 21",
    provinces: [
      "Oyo Province 1",
      "Oyo Province 3",
      "Oyo Province 5",
      "Oyo Province 8",
      "Oyo Province 9",
      "Oyo Province 10",
      "Oyo Province 11",
      "Oyo Province 14",
      "Oyo Province 15",
      "Oyo Province 17",
      "Oyo Province 20",
    ],
  },
  {
    name: "Region 22",
    provinces: [
      "Ondo Province 1",
      "Ondo Province 3",
      "Ondo Province 4",
      "Ondo Province 7",
      "Ondo Province 8",
      "Ondo Province 9",
      "Ondo Province 11",
      "Ondo Province 13",
      "Ondo Province 16",
      "Ondo Province 17",
      "Ondo Province 20",
      "Ondo Province 22",
      "Ondo Province 24",
    ],
  },
  {
    name: "Region 23",
    provinces: [
      "Delta Province 1",
      "Delta Province 2",
      "Delta Province 5",
      "Delta Province 6",
      "Delta Province 12",
      "Delta Province 13",
      "Delta Province 16",
      "Delta Province 20",
      "Delta Province 21",
      "Delta Province 23",
      "Delta Province 25",
      "Delta Province 26",
    ],
  },
  {
    name: "Region 24",
    provinces: [
      "Kogi Province 1",
      "Kogi Province 2",
      "Kogi Province 3",
      "Kogi Province 4",
      "Kogi Province 5",
      "Kogi Province 6",
      "Kogi Province 7",
    ],
  },
  {
    name: "Region 25",
    provinces: [
      "Ekiti Province 1",
      "Ekiti Province 2",
      "Ekiti Province 3",
      "Ekiti Province 4",
      "Ekiti Province 5",
      "Ekiti Province 6",
      "Ekiti Province 7",
      "Ekiti Province 8",
      "Ekiti Province 9",
      "Ekiti Province 10",
      "Ekiti Province 11",
      "Ekiti Province 12",
      "Ekiti Province 13",
    ],
  },
  {
    name: "Region 26",
    provinces: [
      "Lagos Province 22",
      "Lagos Province 41",
      "Lagos Province 58",
      "Lagos Province 63",
      "Lagos Province 75",
      "Lagos Province 97",
    ],
  },
  {
    name: "Region 27",
    provinces: [
      "Bayelsa Province 1",
      "Bayelsa Province 2",
      "Bayelsa Province 3",
      "Bayelsa Province 4",
      "Bayelsa Province 5",
    ],
  },
  {
    name: "Region 28",
    provinces: [
      "Nasarawa Province 1",
      "Nasarawa Province 2",
      "Nasarawa Province 3",
      "Nasarawa Province 4",
      "Nasarawa Province 5",
      "Nasarawa Province 6",
    ],
  },
  {
    name: "Region 29",
    provinces: [
      "Cross River Province 1",
      "Cross River Province 2",
      "Cross River Province 4",
      "Cross River Province 5",
      "Cross River Province 7",
    ],
  },
  {
    name: "Region 30",
    provinces: [
      "Kaduna Province 1",
      "Kaduna Province 2",
      "Kaduna Province 3",
      "Kaduna Province 4",
      "Kaduna Province 5",
      "Kaduna Province 6",
    ],
  },
  {
    name: "Region 31",
    provinces: [
      "Lagos Province 7",
      "Lagos Province 25",
      "Lagos Province 52",
      "Lagos Province 78",
      "Lagos Province 101",
      "Lagos Province 108",
      "Lagos Province 120",
      "Lagos Province 128",
    ],
  },
  {
    name: "Region 32",
    provinces: [
      "Ogun Province 1",
      "Ogun Province 7",
      "Ogun Province 12",
      "Ogun Province 16",
      "Ogun Province 19",
      "Ogun Province 28",
      "Ogun Province 35",
      "Ogun Province 37",
      "Ogun Province 38",
    ],
  },
  {
    name: "Region 33",
    provinces: [
      "Rivers Province 2",
      "Rivers Province 3",
      "Rivers Province 8",
      "Rivers Province 11",
      "Rivers Province 12",
      "Rivers Province 16",
      "Rivers Province 17",
      "Rivers Province 21",
      "Rivers Province 22",
    ],
  },
  {
    name: "Region 34",
    provinces: [
      "Delta Province 3",
      "Delta Province 7",
      "Delta Province 9",
      "Delta Province 14",
      "Delta Province 15",
      "Delta Province 17",
      "Delta Province 24",
    ],
  },
  {
    name: "Region 35",
    provinces: [
      "Youth Province 1",
      "Youth Province 2",
      "Youth Province 5",
      "Youth Province 7",
      "Youth Province 10",
      "Youth Province 13",
      "Youth Province 14",
      "Youth Province 15",
      "Youth Province 16",
      "Youth Province 18",
      "Youth Province 19",
      "Youth Province 20",
    ],
  },
  {
    name: "Region 36",
    provinces: [
      "Lagos Province 12",
      "Lagos Province 18",
      "Lagos Province 30",
      "Lagos Province 38",
      "Lagos Province 72",
      "Lagos Province 90",
      "Lagos Province 91",
      "Lagos Province 94",
      "Lagos Province 121",
      "Lagos Province 122",
    ],
  },
  {
    name: "Region 37",
    provinces: [
      "Lagos Province 10",
      "Lagos Province 17",
      "Lagos Province 42",
      "Lagos Province 49",
      "Lagos Province 57",
      "Lagos Province 83",
      "Lagos Province 96",
      "Lagos Province 123",
      "Lagos Province 129",
    ],
  },
  {
    name: "Region 38",
    provinces: [
      "Edo Province 3",
      "Edo Province 5",
      "Edo Province 7",
      "Edo Province 8",
      "Edo Province 10",
      "Edo Province 12",
      "Edo Province 14",
      "Edo Province 17",
      "Edo Province 18",
    ],
  },
  {
    name: "Region 39",
    provinces: [
      "Ondo Province 2",
      "Ondo Province 5",
      "Ondo Province 6",
      "Ondo Province 10",
      "Ondo Province 12",
      "Ondo Province 14",
      "Ondo Province 15",
      "Ondo Province 18",
      "Ondo Province 19",
      "Ondo Province 21",
      "Ondo Province 23",
    ],
  },
  {
    name: "Region 40",
    provinces: [
      "Benue Province 1",
      "Benue Province 2",
      "Benue Province 3",
      "Benue Province 4",
      "Benue Province 5",
    ],
  },
  {
    name: "Region 41",
    provinces: [
      "Niger Province 1",
      "Niger Province 2",
      "Niger Province 3",
      "Niger Province 4",
      "Niger Province 5",
    ],
  },
  {
    name: "Region 42",
    provinces: [
      "Oyo Province 4",
      "Oyo Province 12",
      "Oyo Province 22",
    ],
  },
  {
    name: "Region 43",
    provinces: [
      "Osun Province 1",
      "Osun Province 4",
      "Osun Province 6",
      "Osun Province 10",
      "Osun Province 13",
      "Osun Province 15",
    ],
  },
  {
    name: "Region 44",
    provinces: [
      "Ogun Province 3",
      "Ogun Province 10",
      "Ogun Province 14",
      "Ogun Province 17",
      "Ogun Province 21",
      "Ogun Province 25",
      "Ogun Province 27",
    ],
  },
  {
    name: "Region 45",
    provinces: [
      "Fct Province 2",
      "Fct Province 5",
      "Fct Province 7",
      "Fct Province 8",
      "Fct Province 14",
      "Fct Province 16",
      "Fct Province 22 Main",
    ],
  },
  {
    name: "Region 46",
    provinces: [
      "Fct Province 3",
      "Fct Province 9",
      "Fct Province 10",
      "Fct Province 11",
      "Fct Province 17",
      "Fct Province 18",
      "Fct Province 20",
    ],
  },
  {
    name: "Region 47",
    provinces: [
      "Anambra Province 1",
      "Anambra Province 2",
      "Anambra Province 3",
      "Anambra Province 4",
      "Anambra Province 5",
    ],
  },
  {
    name: "Region 48",
    provinces: [
      "Imo Province 1",
      "Imo Province 2",
      "Imo Province 3",
      "Imo Province 4",
    ],
  },
  {
    name: "Region 49",
    provinces: [
      "Akwa Ibom Province 2",
      "Akwa Ibom Province 4",
      "Akwa Ibom Province 11",
      "Akwa Ibom Province 12",
    ],
  },
  {
    name: "Region 50",
    provinces: [
      "Delta Province 4",
      "Delta Province 8",
      "Delta Province 10",
      "Delta Province 11",
      "Delta Province 18",
      "Delta Province 19",
      "Delta Province 22",
    ],
  },
  {
    name: "Region 51",
    provinces: [
      "Lagos Province 5",
      "Lagos Province 24",
      "Lagos Province 39",
      "Lagos Province 46",
      "Lagos Province 48",
      "Lagos Province 66",
      "Lagos Province 132",
    ],
  },
  {
    name: "Region 52",
    provinces: [
      "Lagos Province 26",
      "Lagos Province 31",
      "Lagos Province 45",
      "Lagos Province 71",
      "Lagos Province 74",
      "Lagos Province 82",
      "Lagos Province 109",
    ],
  },
  {
    name: "Region 53",
    provinces: [
      "Lagos Province 14",
      "Lagos Province 51",
      "Lagos Province 85",
      "Lagos Province 105",
      "Lagos Province 106",
      "Lagos Province 112",
    ],
  },
  {
    name: "Region 54",
    provinces: [
      "Lagos Province 3",
      "Lagos Province 32",
      "Lagos Province 44",
      "Lagos Province 61",
      "Lagos Province 81",
      "Lagos Province 116",
      "Lagos Province 117",
      "Lagos Province 130",
    ],
  },
  {
    name: "Region 55",
    provinces: [
      "Rivers Province 5",
      "Rivers Province 7",
      "Rivers Province 10",
      "Rivers Province 13",
      "Rivers Province 20",
      "Rivers Province 23",
    ],
  },
  {
    name: "Region 56",
    provinces: [
      "Cross River Province 3",
      "Cross River Province 6",
      "Cross River Province 8",
      "Cross River Province 9",
    ],
  },
  {
    name: "Region 57",
    provinces: [
      "Akwa Ibom Province 1",
      "Akwa Ibom Province 8",
      "Akwa Ibom Province 10",
      "Akwa Ibom Province 13",
    ],
  },
  {
    name: "Region 58",
    provinces: [
      "Ogun Province 2",
      "Ogun Province 9",
      "Ogun Province 13",
      "Ogun Province 24",
      "Ogun Province 29",
      "Ogun Province 32",
      "Ogun Province 36",
    ],
  },
  {
    name: "Region 59",
    provinces: [
      "Lagos Province 19",
      "Lagos Province 21",
      "Lagos Province 36",
      "Lagos Province 54",
      "Lagos Province 64",
      "Lagos Province 76",
      "Lagos Province 100",
      "Lagos Province 113",
    ],
  },
  {
    name: "Region 60",
    provinces: [
      "Oyo Province 2",
      "Oyo Province 6",
      "Oyo Province 7",
      "Oyo Province 13",
      "Oyo Province 16",
      "Oyo Province 18",
      "Oyo Province 19",
      "Oyo Province 21",
      "Oyo Province 23",
      "Oyo Province 24",
    ],
  },
  {
    name: "Region 61",
    provinces: [
      "Lagos Province 29",
      "Lagos Province 37",
      "Lagos Province 59",
      "Lagos Province 68",
      "Lagos Province 80",
      "Lagos Province 102",
    ],
  },
  {
    name: "Region 62",
    provinces: [
      "Ogun Province 6",
      "Ogun Province 15",
      "Ogun Province 26",
      "Ogun Province 34",
    ],
  },
  {
    name: "Region 63",
    provinces: [
      "Lagos Province 9",
      "Lagos Province 28",
      "Lagos Province 69",
      "Lagos Province 84",
      "Lagos Province 86",
      "Lagos Province 104",
    ],
  },
  {
    name: "Region 64",
    provinces: [
      "Lagos Province 33",
      "Lagos Province 55",
      "Lagos Province 62",
      "Lagos Province 98",
      "Lagos Province 99",
      "Lagos Province 107",
    ],
  },
  {
    name: "Region 65",
    provinces: [
      "Youth Province 3",
      "Youth Province 4",
      "Youth Province 6",
      "Youth Province 8",
      "Youth Province 9",
      "Youth Province 11",
      "Youth Province 12",
      "Youth Province 17",
    ],
  },
]
